#! python3

# SD Computing Studies Assignment
'''
##### Task 4
Dungeons and Dragons Character Generator
In Dungeons and Dragons, players roll 3 dice to generate statistics for their characters.  The statistics recorded are:
strength
intelligence
wisdom
dexterity
constitution
charisma
Create a character generator that generates a character's statistics
(3 points)
'''
import random
print("\n\n<<< Dungeons and Dragons Character Generator >>>\n")

def playerRolls():
    a = random.randint(1,6)
    b = random.randint(1,6)
    c = random.randint(1,6)
    return [a,b,c]

def main():
    names = ["Boo Radley", "Scout", "Atticus", "Aunty Alexandra", "Uncle Finch", "Miss Maudie Atkinson", "Jem", "Gregor Samsa", "Old Major", "Snowball", "Napoleon", "Squealer", "Jones", "Boxer", "Mollie", "Romeo Montague", "Juliet Capulet", "Mercutio", "Tybalt", "The Nurse", "Friar Laurence","Winston Smith", "Julia", "O'Brien", "Katherine", "Big Brother", "Goldstein", "Catherine", "Heathcliff", "Edgar Linton", "Little Cathy Linton", "Hareton Earnshaw", "Ellen Dean", "Ralph", "Piggy", "Jack", "Simon", "Samneric", "Percival Wemys Madison", "Lennie Small", "George Milton", "Slim", "Candy", "Curley", "Liesel Meminger", "Hans Hubermann", "Rosa Hubermann", "Rudy Steiner", "Max Vandenburg"]

    stats = ["strength", "intelligence", "wisdom", "dexterity", "constitution", "charisma"]

    while __name__ == "__main__":
        playerName = input("Enter a name for your character (or it will be autogenerated): ")

        if playerName == "":
            playerName = random.choice(names)
        else:
            playerName == playerName

        print(f"\nYour character's name is {playerName}\n")
        print(f"{playerName}'s statistics")
        for i in stats:
            roll = playerRolls()
            print(f"{i}: {roll[0] + roll[1] + roll[2]}")
        
        break


main()